import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Mia',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Mel',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: 'Bacchante’ Print',
      slug: 'bacchante',
      category: 'Prints',
      image: '/images/print01.jpg',
      price: 20,
      brand: 'Tim Furlow',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular print',
    },
    {
      name: 'Surrealist Hell Print',
      slug: 'surrealist-hell',
      category: 'Prints',
      image: '/images/print02.jpg',
      price: 20,
      brand: 'Tim Furlow',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular print',
    },
    {
      name: 'The Modern Prometheus Print',
      slug: 'modern-prometheus',
      category: 'Prints',
      image: '/images/print03.jpg',
      price: 20,
      brand: 'Tim Furlow',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular print',
    },
    {
      name: 'The Protectress Print',
      slug: 'protectress',
      category: 'Prints',
      image: '/images/print04.jpg',
      price: 20,
      brand: 'Tim Furlow',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular print',
    },
    {
      name: 'Cash Print',
      slug: 'cash',
      category: 'Prints',
      image: '/images/print05.jpg',
      price: 20,
      brand: 'Tim Furlow',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular print',
    },
    {
      name: 'Dweller on the threshold Print',
      slug: 'dweller',
      category: 'Prints',
      image: '/images/print06.jpg',
      price: 20,
      brand: 'Tim Furlow',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular print',
    },
    {
      name: 'John Oliver Print',
      slug: 'oliver',
      category: 'Prints',
      image: '/images/print07.jpg',
      price: 20,
      brand: 'Tim Furlow',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular print',
    },
    {
      name: 'Venus in the Garden Print',
      slug: 'venus',
      category: 'Prints',
      image: '/images/print08.jpg',
      price: 20,
      brand: 'Tim Furlow',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular print',
    },
    {
      name: 'Completion Print',
      slug: 'completion',
      category: 'Prints',
      image: '/images/print09.jpg',
      price: 20,
      brand: 'Tim Furlow',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular print',
    },
    {
      name: 'Alan Rickman Print',
      slug: 'mr-rickman',
      category: 'Prints',
      image: '/images/print10.jpg',
      price: 20,
      brand: 'Tim Furlow',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular print',
    },
  ],
};
export default data;
